apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-test-pv
spec:
  storageClassName: mc-sc
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 16Gi
  persistentVolumeReclaimPolicy: Retain
#TODO FINISH THIS
