apiVersion: v1
kind: Service
metadata:
  name: mc-test-svc
spec:
  type: NodePort
  ports:
  - port: 25565
  selector:
    app: minecraft
    instance: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-test-deploy
spec:
  selector:
    matchLabels:
      app: minecraft
      instance: test
  template:
    metadata:
      labels:
        app: minecraft
        instance: test
    spec:
      containers:
      - name: mc-test-pod
        image: cobalt32/minecraft:1.16.5
        imagePullPolicy: Always
        ports:
        - containerPort: 25565