FROM alpine
WORKDIR /srv/minecraft
RUN apk add --no-cache openjdk16-jre-headless && \
wget https://launcher.mojang.com/v1/objects/a16d67e5807f57fc4e550299cf20226194497dc2/server.jar
COPY copy .
EXPOSE 25565
ENTRYPOINT ["java"]
CMD ["-Xms2G", "-Xmx4G", "-jar", "server.jar", "nogui"]
